name: EasyKarma
version: '1.0.0-BETA'
main: org.legion.easyKarma.EasyKarma
description: "A Karma Minecraft plugin"
api-version: '1.20'

commands:
  karma:
    description: Main karma command
    usage: /karma <args>
permissions:
  easykarma.admin:
    description: Allows players to use karma commands.
    default: false
